spring.application.name=untilMoraleImproves2

spring.datasource.url=jdbc:postgresql://localhost:5432/testdatabase
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

cors.allowed-origins=http://localhost:3000,http://localhost:8080

logging.level.org.springframework.security=TRACE
logging.level.org.morgan.untilmoraleimproves2=DEBUG
logging.file.name=logs/application.log
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

app.jwtSecret= 0c98713d4e197f1698cc595c9c5c3e40a6c6c9f5e9629b80
app.jwtExpirationMs= 86400000